apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: woiof1v60-python 
  janus-idp.io/tekton: woiof1v60-python
  backstage.io/kubernetes-id: woiof1v60-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: woiof1v60-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml