apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: woiof1v60-python
  janus-idp.io/tekton: woiof1v60-python
  backstage.io/kubernetes-id: woiof1v60-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: woiof1v60-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
