apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: woiof1v60-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: woiof1v60-python 
  name: woiof1v60-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: woiof1v60-python 
